/*
* Generated file
*
* Generated from: yang module name: tsdr-collector-spi yang module local name: tsdr-collector-spi
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Sep 15 17:04:31 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.tsdr.collector.spi;
public class TSDRCollectorSPIModuleFactory extends org.opendaylight.controller.config.yang.config.tsdr.collector.spi.AbstractTSDRCollectorSPIModuleFactory {

}
