/**
 * Copyright (c) 2015 Cisco Systems, Inc. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: tsdr-collector-spi yang module local name: tsdr-collector-spi
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Sep 15 17:04:31 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.tsdr.collector.spi;
public class TSDRCollectorSPIModuleFactory extends org.opendaylight.controller.config.yang.config.tsdr.collector.spi.AbstractTSDRCollectorSPIModuleFactory {

}
