/*
 * Copyright (c) 2015 Dell Inc. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: TSDR-datastorage-impl yang module local name: TSDR-datastorage-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Feb 21 12:19:10 EST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.TSDR_datastorage.impl;

import org.opendaylight.controller.config.api.DependencyResolver;
import org.osgi.framework.BundleContext;

public class TSDRDatastorageModuleFactory extends org.opendaylight.controller.config.yang.config.TSDR_datastorage.impl.AbstractTSDRDatastorageModuleFactory {
    @Override
    public TSDRDatastorageModule instantiateModule(String instanceName, DependencyResolver dependencyResolver, TSDRDatastorageModule oldModule, AutoCloseable oldInstance, BundleContext bundleContext) {
        TSDRDatastorageModule module = super.instantiateModule(instanceName, dependencyResolver, oldModule, oldInstance, bundleContext);
        module.setBundleContext(bundleContext);
        return module;
    }

    @Override
    public TSDRDatastorageModule instantiateModule(String instanceName, DependencyResolver dependencyResolver, BundleContext bundleContext) {
        TSDRDatastorageModule module = super.instantiateModule(instanceName, dependencyResolver, bundleContext);
        module.setBundleContext(bundleContext);
        return module;
    }
}
