/*
 * Copyright (c) 2016 Cisco Inc. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: tsdr-sflow-statistics-collector yang module local name: tsdr-sflow-statistics-collector
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Jun 04 11:37:51 PDT 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.tsdr.sflow.statistics.collector;
public class TSDRSFlowCollectorModuleFactory extends org.opendaylight.controller.config.yang.config.tsdr.sflow.statistics.collector.AbstractTSDRSFlowCollectorModuleFactory {

}
