/*
* Generated file
*
* Generated from: yang module name: TSDRDC yang module local name: TSDRDC
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Mar 14 08:16:21 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.TSDRDC;
public class TSDRDCModuleFactory extends org.opendaylight.controller.config.yang.config.TSDRDC.AbstractTSDRDCModuleFactory {

}
