/*
 * Copyright (c) 2015 Tata Consultancy Services, Inc. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: tsdr-snmp-data-collector yang module local name: tsdr-snmp-data-collector
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Oct 13 12:50:32 IST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.tsdr.snmp.data.collector;

import org.opendaylight.controller.config.api.DependencyResolver;
import org.osgi.framework.BundleContext;

public class TSDRSnmpDataCollectorModuleFactory extends org.opendaylight.controller.config.yang.config.tsdr.snmp.data.collector.AbstractTSDRSnmpDataCollectorModuleFactory {
    @Override
    public TSDRSnmpDataCollectorModule instantiateModule(String instanceName, DependencyResolver dependencyResolver, TSDRSnmpDataCollectorModule oldModule, AutoCloseable oldInstance, BundleContext bundleContext) {
        TSDRSnmpDataCollectorModule module =  super.instantiateModule(instanceName, dependencyResolver, oldModule, oldInstance, bundleContext);
        module.setBundleContext(bundleContext);
        return module;
    }

    @Override
    public TSDRSnmpDataCollectorModule instantiateModule(String instanceName, DependencyResolver dependencyResolver, BundleContext bundleContext) {
        TSDRSnmpDataCollectorModule module = super.instantiateModule(instanceName, dependencyResolver, bundleContext);
        module.setBundleContext(bundleContext);
        return module;
    }
}
