/*
* Generated file
*
* Generated from: yang module name: tsdr-snmp-data-collector yang module local name: tsdr-snmp-data-collector
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Oct 13 12:50:32 IST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.tsdr.snmp.data.collector;
public class TSDRSDCModuleFactory extends org.opendaylight.controller.config.yang.config.tsdr.snmp.data.collector.AbstractTSDRSDCModuleFactory {

}
