/*
* Generated file
*
* Generated from: yang module name: tsdr-openflow-statistics-collector yang module local name: tsdr-openflow-statistics-collector
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Aug 20 10:30:13 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.tsdr.openflow.statistics.collector;
public class TSDROSCModuleFactory extends org.opendaylight.controller.config.yang.config.tsdr.openflow.statistics.collector.AbstractTSDROSCModuleFactory {

}
