/*
* Generated file
*
* Generated from: yang module name: tsdr-external-collector-service yang module local name: tsdr-external-collector-service
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Aug 28 13:48:11 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.tsdr.controller.metrics.collector;
public class TSDRECSModuleFactory extends org.opendaylight.controller.config.yang.config.tsdr.controller.metrics.collector.AbstractTSDRECSModuleFactory {

}
