/*
 * Copyright (c) 2015 Cisco Systems, Inc. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: tsdr-configuration yang module local name: tsdr-configuration
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Nov 30 14:23:27 PST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.tsdr.configuration;

import org.opendaylight.controller.config.api.DependencyResolver;
import org.osgi.framework.BundleContext;

public class TSDRConfigModuleFactory extends org.opendaylight.controller.config.yang.config.tsdr.configuration.AbstractTSDRConfigModuleFactory {
    @Override
    public TSDRConfigModule instantiateModule(String instanceName, DependencyResolver dependencyResolver, TSDRConfigModule oldModule, AutoCloseable oldInstance, BundleContext bundleContext) {
        TSDRConfigModule module = super.instantiateModule(instanceName, dependencyResolver, oldModule, oldInstance, bundleContext);
        module.setBundleContext(bundleContext);
        return module;
    }

    @Override
    public TSDRConfigModule instantiateModule(String instanceName, DependencyResolver dependencyResolver, BundleContext bundleContext) {
        TSDRConfigModule module = super.instantiateModule(instanceName, dependencyResolver, bundleContext);
        module.setBundleContext(bundleContext);
        return module;
    }
}
