/*
* Generated file
*
* Generated from: yang module name: tsdr-northbound-api yang module local name: tsdr-northbound-api
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Oct 13 08:42:29 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.tsdr.northbound.api;
public class TSDRNBIModuleFactory extends org.opendaylight.controller.config.yang.config.tsdr.northbound.api.AbstractTSDRNBIModuleFactory {

}
