/*
 * Copyright (c) 2015 Scott Melton All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: TSDR-dataquery-impl yang module local name: TSDR-dataquery-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Feb 21 12:19:10 EST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.TSDR_dataquery.impl;
public class TSDRDataqueryModuleFactory extends org.opendaylight.controller.config.yang.config.TSDR_dataquery.impl.AbstractTSDRDataqueryModuleFactory {

}
