/*
 * Copyright (c) 2016 Saugo360.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: tsdr-restconf-collector yang module local name: tsdr-restconf-collector
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Nov 17 20:02:46 EEST 2016
*
* Do not modify this file unless it is present under src/main directory
*/

/**
 * This class is a factory for the module. It creates our module and provides it with its bundle context needed
 * for registering the filter and the configuration class
 *
 * @author <a href="mailto:a.alhamali93@gmail.com">AbdulRahman AlHamali</a>
 *
 *         Created: Dec 16th, 2016
 *
 */
package org.opendaylight.controller.config.yang.config.tsdr.restconf.collector;

public class TSDRRestconfCollectorModuleFactory extends
    org.opendaylight.controller.config.yang.config.tsdr.restconf.collector.AbstractTSDRRestconfCollectorModuleFactory {

    @Override
    public org.opendaylight.controller.config.spi.Module createModule(String instanceName,
        org.opendaylight.controller.config.api.DependencyResolver dependencyResolver,
        org.osgi.framework.BundleContext bundleContext) {

        TSDRRestconfCollectorModule module
            = (TSDRRestconfCollectorModule) super.createModule(instanceName,
            dependencyResolver, bundleContext);

        module.setBundleContext(bundleContext);

        return module;
    }

    @Override
    public org.opendaylight.controller.config.spi.Module createModule(String instanceName,
        org.opendaylight.controller.config.api.DependencyResolver dependencyResolver,
        org.opendaylight.controller.config.api.DynamicMBeanWithInstance old,
        org.osgi.framework.BundleContext bundleContext) throws Exception {

        TSDRRestconfCollectorModule module
            = (TSDRRestconfCollectorModule) super.createModule(instanceName,
            dependencyResolver, old, bundleContext);

        module.setBundleContext(bundleContext);

        return module;
    }
}
