/*
 * Copyright (c) 2015 Cisco Systems, Inc. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: tsdr-syslog-collector yang module local name: tsdr-syslog-collector
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Oct 07 09:56:30 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.tsdr_syslog_collector;
public class TSDRSyslogModuleFactory extends org.opendaylight.controller.config.yang.config.tsdr_syslog_collector.AbstractTSDRSyslogModuleFactory {

}
