/**
 * Copyright (c) 2015 Cisco Systems, Inc. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: tsdr-controller-metrics-collector yang module local name: tsdr-controller-metrics-collector
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Aug 20 15:08:00 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.tsdr.controller.metrics.collector;
public class TSDRCMCModuleFactory extends org.opendaylight.controller.config.yang.config.tsdr.controller.metrics.collector.AbstractTSDRCMCModuleFactory {

}
