/*
* Generated file
*
* Generated from: yang module name: tsdr-netflow-statistics-collector yang module local name: tsdr-netflow-statistics-collector
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Oct 12 02:10:57 EDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.tsdr.netflow.statistics.collector;
public class TSDRNetFlowCollectorModuleFactory extends org.opendaylight.controller.config.yang.config.tsdr.netflow.statistics.collector.AbstractTSDRNetFlowCollectorModuleFactory {

}
