/*
* Generated file
*
* Generated from: yang module name: TSDR-datapurge-impl yang module local name: TSDR-datapurge-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Sep 25 19:43:35 EDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.TSDR_datapurge.impl;
public class TSDRDatastorageModuleFactory extends org.opendaylight.controller.config.yang.config.TSDR_datapurge.impl.AbstractTSDRDatastorageModuleFactory {

}
