/*
* Generated file
*
* Generated from: yang module name: TSDR-datapurge-impl yang module local name: TSDR-datapurge-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Sep 28 20:46:52 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.TSDR_datapurge.impl;
public class TSDRDatapurgeModuleFactory extends org.opendaylight.controller.config.yang.config.TSDR_datapurge.impl.AbstractTSDRDatapurgeModuleFactory {

}
