/*
 * Copyright (c) 2015 Shoaib Rao All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: TSDR-datapurge-impl yang module local name: TSDR-datapurge-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Sep 28 20:46:52 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.TSDR_datapurge.impl;

import org.opendaylight.controller.config.api.DependencyResolver;
import org.osgi.framework.BundleContext;

public class TSDRDatapurgeModuleFactory extends org.opendaylight.controller.config.yang.config.TSDR_datapurge.impl.AbstractTSDRDatapurgeModuleFactory {
    @Override
    public TSDRDatapurgeModule instantiateModule(String instanceName, DependencyResolver dependencyResolver, TSDRDatapurgeModule oldModule, AutoCloseable oldInstance, BundleContext bundleContext) {
        TSDRDatapurgeModule module = super.instantiateModule(instanceName, dependencyResolver, oldModule, oldInstance, bundleContext);
        module.setBundleContext(bundleContext);
        return module;
    }

    @Override
    public TSDRDatapurgeModule instantiateModule(String instanceName, DependencyResolver dependencyResolver, BundleContext bundleContext) {
        TSDRDatapurgeModule module = super.instantiateModule(instanceName, dependencyResolver, bundleContext);
        module.setBundleContext(bundleContext);
        return module;
    }
}
